# CMake generated Testfile for 
# Source directory: /mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master
# Build directory: /mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(create_primal_smooth_def "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--upper_dim" "9223372036854775807" "smooth_16.complex" "primal_smooth_def.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_primal_smooth_def PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_primal_smooth_def "/usr/bin/cmake" "-E" "compare_files" "primal_smooth_def.DIPHA_TEST" "smooth_def.diagram")
SET_TESTS_PROPERTIES(compare_primal_smooth_def PROPERTIES  DEPENDS "create_primal_smooth_def" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_dual_smooth_def "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--dual" "--upper_dim" "9223372036854775807" "smooth_16.complex" "dual_smooth_def.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_dual_smooth_def PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_dual_smooth_def "/usr/bin/cmake" "-E" "compare_files" "dual_smooth_def.DIPHA_TEST" "smooth_def.diagram")
SET_TESTS_PROPERTIES(compare_dual_smooth_def PROPERTIES  DEPENDS "create_dual_smooth_def" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_primal_smooth_2 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--upper_dim" "2" "smooth_16.complex" "primal_smooth_2.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_primal_smooth_2 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_primal_smooth_2 "/usr/bin/cmake" "-E" "compare_files" "primal_smooth_2.DIPHA_TEST" "smooth_2.diagram")
SET_TESTS_PROPERTIES(compare_primal_smooth_2 PROPERTIES  DEPENDS "create_primal_smooth_2" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_dual_smooth_2 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--dual" "--upper_dim" "2" "smooth_16.complex" "dual_smooth_2.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_dual_smooth_2 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_dual_smooth_2 "/usr/bin/cmake" "-E" "compare_files" "dual_smooth_2.DIPHA_TEST" "smooth_2.diagram")
SET_TESTS_PROPERTIES(compare_dual_smooth_2 PROPERTIES  DEPENDS "create_dual_smooth_2" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_primal_noise_3_16_def "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--upper_dim" "9223372036854775807" "noise_3_16.complex" "primal_noise_3_16_def.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_primal_noise_3_16_def PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_primal_noise_3_16_def "/usr/bin/cmake" "-E" "compare_files" "primal_noise_3_16_def.DIPHA_TEST" "noise_3_16_def.diagram")
SET_TESTS_PROPERTIES(compare_primal_noise_3_16_def PROPERTIES  DEPENDS "create_primal_noise_3_16_def" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_dual_noise_3_16_def "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--dual" "--upper_dim" "9223372036854775807" "noise_3_16.complex" "dual_noise_3_16_def.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_dual_noise_3_16_def PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_dual_noise_3_16_def "/usr/bin/cmake" "-E" "compare_files" "dual_noise_3_16_def.DIPHA_TEST" "noise_3_16_def.diagram")
SET_TESTS_PROPERTIES(compare_dual_noise_3_16_def PROPERTIES  DEPENDS "create_dual_noise_3_16_def" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_primal_noise_4_8_def "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--upper_dim" "9223372036854775807" "noise_4_8.complex" "primal_noise_4_8_def.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_primal_noise_4_8_def PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_primal_noise_4_8_def "/usr/bin/cmake" "-E" "compare_files" "primal_noise_4_8_def.DIPHA_TEST" "noise_4_8_def.diagram")
SET_TESTS_PROPERTIES(compare_primal_noise_4_8_def PROPERTIES  DEPENDS "create_primal_noise_4_8_def" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_dual_noise_4_8_def "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--dual" "--upper_dim" "9223372036854775807" "noise_4_8.complex" "dual_noise_4_8_def.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_dual_noise_4_8_def PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_dual_noise_4_8_def "/usr/bin/cmake" "-E" "compare_files" "dual_noise_4_8_def.DIPHA_TEST" "noise_4_8_def.diagram")
SET_TESTS_PROPERTIES(compare_dual_noise_4_8_def PROPERTIES  DEPENDS "create_dual_noise_4_8_def" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_primal_ramp_3_16_def "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--upper_dim" "9223372036854775807" "ramp_3_16.complex" "primal_ramp_3_16_def.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_primal_ramp_3_16_def PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_primal_ramp_3_16_def "/usr/bin/cmake" "-E" "compare_files" "primal_ramp_3_16_def.DIPHA_TEST" "ramp_3_16_def.diagram")
SET_TESTS_PROPERTIES(compare_primal_ramp_3_16_def PROPERTIES  DEPENDS "create_primal_ramp_3_16_def" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_dual_ramp_3_16_def "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--dual" "--upper_dim" "9223372036854775807" "ramp_3_16.complex" "dual_ramp_3_16_def.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_dual_ramp_3_16_def PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_dual_ramp_3_16_def "/usr/bin/cmake" "-E" "compare_files" "dual_ramp_3_16_def.DIPHA_TEST" "ramp_3_16_def.diagram")
SET_TESTS_PROPERTIES(compare_dual_ramp_3_16_def PROPERTIES  DEPENDS "create_dual_ramp_3_16_def" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_primal_ramp_4_8_def "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--upper_dim" "9223372036854775807" "ramp_4_8.complex" "primal_ramp_4_8_def.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_primal_ramp_4_8_def PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_primal_ramp_4_8_def "/usr/bin/cmake" "-E" "compare_files" "primal_ramp_4_8_def.DIPHA_TEST" "ramp_4_8_def.diagram")
SET_TESTS_PROPERTIES(compare_primal_ramp_4_8_def PROPERTIES  DEPENDS "create_primal_ramp_4_8_def" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_dual_ramp_4_8_def "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--dual" "--upper_dim" "9223372036854775807" "ramp_4_8.complex" "dual_ramp_4_8_def.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_dual_ramp_4_8_def PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_dual_ramp_4_8_def "/usr/bin/cmake" "-E" "compare_files" "dual_ramp_4_8_def.DIPHA_TEST" "ramp_4_8_def.diagram")
SET_TESTS_PROPERTIES(compare_dual_ramp_4_8_def PROPERTIES  DEPENDS "create_dual_ramp_4_8_def" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_primal_sphere_3 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--upper_dim" "3" "sphere_3_32.complex" "primal_sphere_3.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_primal_sphere_3 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_primal_sphere_3 "/usr/bin/cmake" "-E" "compare_files" "primal_sphere_3.DIPHA_TEST" "sphere_3.diagram")
SET_TESTS_PROPERTIES(compare_primal_sphere_3 PROPERTIES  DEPENDS "create_primal_sphere_3" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_dual_sphere_3 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--dual" "--upper_dim" "3" "sphere_3_32.complex" "dual_sphere_3.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_dual_sphere_3 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_dual_sphere_3 "/usr/bin/cmake" "-E" "compare_files" "dual_sphere_3.DIPHA_TEST" "sphere_3.diagram")
SET_TESTS_PROPERTIES(compare_dual_sphere_3 PROPERTIES  DEPENDS "create_dual_sphere_3" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_primal_sphere_2 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--upper_dim" "2" "sphere_3_32.complex" "primal_sphere_2.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_primal_sphere_2 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_primal_sphere_2 "/usr/bin/cmake" "-E" "compare_files" "primal_sphere_2.DIPHA_TEST" "sphere_2.diagram")
SET_TESTS_PROPERTIES(compare_primal_sphere_2 PROPERTIES  DEPENDS "create_primal_sphere_2" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_dual_sphere_2 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--dual" "--upper_dim" "2" "sphere_3_32.complex" "dual_sphere_2.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_dual_sphere_2 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_dual_sphere_2 "/usr/bin/cmake" "-E" "compare_files" "dual_sphere_2.DIPHA_TEST" "sphere_2.diagram")
SET_TESTS_PROPERTIES(compare_dual_sphere_2 PROPERTIES  DEPENDS "create_dual_sphere_2" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_primal_sphere_1 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--upper_dim" "1" "sphere_3_32.complex" "primal_sphere_1.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_primal_sphere_1 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_primal_sphere_1 "/usr/bin/cmake" "-E" "compare_files" "primal_sphere_1.DIPHA_TEST" "sphere_1.diagram")
SET_TESTS_PROPERTIES(compare_primal_sphere_1 PROPERTIES  DEPENDS "create_primal_sphere_1" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_dual_sphere_1 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--dual" "--upper_dim" "1" "sphere_3_32.complex" "dual_sphere_1.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_dual_sphere_1 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_dual_sphere_1 "/usr/bin/cmake" "-E" "compare_files" "dual_sphere_1.DIPHA_TEST" "sphere_1.diagram")
SET_TESTS_PROPERTIES(compare_dual_sphere_1 PROPERTIES  DEPENDS "create_dual_sphere_1" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_primal_sphere_3_2 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--upper_dim" "3" "sphere_3_32_2.complex" "primal_sphere_3_2.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_primal_sphere_3_2 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_primal_sphere_3_2 "/usr/bin/cmake" "-E" "compare_files" "primal_sphere_3_2.DIPHA_TEST" "sphere_3_2.diagram")
SET_TESTS_PROPERTIES(compare_primal_sphere_3_2 PROPERTIES  DEPENDS "create_primal_sphere_3_2" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_dual_sphere_3_2 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--dual" "--upper_dim" "3" "sphere_3_32_2.complex" "dual_sphere_3_2.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_dual_sphere_3_2 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_dual_sphere_3_2 "/usr/bin/cmake" "-E" "compare_files" "dual_sphere_3_2.DIPHA_TEST" "sphere_3_2.diagram")
SET_TESTS_PROPERTIES(compare_dual_sphere_3_2 PROPERTIES  DEPENDS "create_dual_sphere_3_2" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_primal_sphere_3_0.8 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--upper_dim" "3" "sphere_3_32_0.8.complex" "primal_sphere_3_0.8.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_primal_sphere_3_0.8 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_primal_sphere_3_0.8 "/usr/bin/cmake" "-E" "compare_files" "primal_sphere_3_0.8.DIPHA_TEST" "sphere_3_0.8.diagram")
SET_TESTS_PROPERTIES(compare_primal_sphere_3_0.8 PROPERTIES  DEPENDS "create_primal_sphere_3_0.8" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_dual_sphere_3_0.8 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--dual" "--upper_dim" "3" "sphere_3_32_0.8.complex" "dual_sphere_3_0.8.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_dual_sphere_3_0.8 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_dual_sphere_3_0.8 "/usr/bin/cmake" "-E" "compare_files" "dual_sphere_3_0.8.DIPHA_TEST" "sphere_3_0.8.diagram")
SET_TESTS_PROPERTIES(compare_dual_sphere_3_0.8 PROPERTIES  DEPENDS "create_dual_sphere_3_0.8" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_primal_sphere_2_0.5 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--upper_dim" "2" "sphere_3_32_0.5.complex" "primal_sphere_2_0.5.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_primal_sphere_2_0.5 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_primal_sphere_2_0.5 "/usr/bin/cmake" "-E" "compare_files" "primal_sphere_2_0.5.DIPHA_TEST" "sphere_2_0.5.diagram")
SET_TESTS_PROPERTIES(compare_primal_sphere_2_0.5 PROPERTIES  DEPENDS "create_primal_sphere_2_0.5" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_dual_sphere_2_0.5 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--dual" "--upper_dim" "2" "sphere_3_32_0.5.complex" "dual_sphere_2_0.5.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_dual_sphere_2_0.5 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_dual_sphere_2_0.5 "/usr/bin/cmake" "-E" "compare_files" "dual_sphere_2_0.5.DIPHA_TEST" "sphere_2_0.5.diagram")
SET_TESTS_PROPERTIES(compare_dual_sphere_2_0.5 PROPERTIES  DEPENDS "create_dual_sphere_2_0.5" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_primal_sphere_1_0.3 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--upper_dim" "2" "sphere_3_32_0.3.complex" "primal_sphere_1_0.3.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_primal_sphere_1_0.3 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_primal_sphere_1_0.3 "/usr/bin/cmake" "-E" "compare_files" "primal_sphere_1_0.3.DIPHA_TEST" "sphere_1_0.3.diagram")
SET_TESTS_PROPERTIES(compare_primal_sphere_1_0.3 PROPERTIES  DEPENDS "create_primal_sphere_1_0.3" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_dual_sphere_1_0.3 "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--dual" "--upper_dim" "2" "sphere_3_32_0.3.complex" "dual_sphere_1_0.3.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_dual_sphere_1_0.3 PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_dual_sphere_1_0.3 "/usr/bin/cmake" "-E" "compare_files" "dual_sphere_1_0.3.DIPHA_TEST" "sphere_1_0.3.diagram")
SET_TESTS_PROPERTIES(compare_dual_sphere_1_0.3 PROPERTIES  DEPENDS "create_dual_sphere_1_0.3" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_dualize "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dualize" "primal_explicit.complex" "dualize.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_dualize PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_dualize "/usr/bin/cmake" "-E" "compare_files" "dualize.DIPHA_TEST" "dual_explicit.complex")
SET_TESTS_PROPERTIES(compare_dualize PROPERTIES  DEPENDS "create_dualize" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_primal_explicit "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "primal_explicit.complex" "primal_explicit.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_primal_explicit PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_primal_explicit "/usr/bin/cmake" "-E" "compare_files" "primal_explicit.DIPHA_TEST" "explicit.diagram")
SET_TESTS_PROPERTIES(compare_primal_explicit PROPERTIES  DEPENDS "create_primal_explicit" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(create_dual_explicit "/usr/bin/mpiexec" "-n" "10" "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/dipha" "--dual" "dual_explicit.complex" "dual_explicit.DIPHA_TEST")
SET_TESTS_PROPERTIES(create_dual_explicit PROPERTIES  WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
ADD_TEST(compare_dual_explicit "/usr/bin/cmake" "-E" "compare_files" "dual_explicit.DIPHA_TEST" "explicit.diagram")
SET_TESTS_PROPERTIES(compare_dual_explicit PROPERTIES  DEPENDS "create_dual_explicit" WORKING_DIRECTORY "/mnt/c/Users/jdbba/OneDrive/Documents/School/Research/Software/dipha-master/dipha-master/test_data")
